[package]
name = "migrations"
version.workspace = true
edition.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
ensemble = { workspace = true }
dotenv = { workspace = true }
