[package]
name = "macros"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
glob = "0.3.1"
proc-macro2 = "1.0.66"
quote = "1.0.33"
regex = "1.9.5"
